### ISSUE TITLE
indexPath.column has value of 2147483647 in cellForRowAtIndexPath when not using storyboarding

### ISSUE THREAD

**Issue by patmalt** [KieranLafferty/KLScrollSelect#2] opened 2013-06-06 03:32 UTC
indexPath.column has a value of 2147483647, which equals NSIntegerMax and NSNotFound.

When I used storyboarding, it worked perfectly. However when I am developing a project without storyboarding, I crash at:
- (UITableViewCell_) scrollSelect:(KLScrollSelect_) scrollSelect cellForRowAtIndexPath:(NSIndexPath *)indexPath

specifically:

KLScrollingColumn\* column = [[scrollSelect columns] objectAtIndex: indexPath.column];.

Message from Console:

NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 2147483647 beyond bounds [0 .. 4]'

I set up the interface the same exact way for both. Drag a new view onto the main view, change the views class to KLScrollSelect, connect the scroll select data source and delegate to the File's Owner and connect the File's Owner to the scroll select.

![screen shot 2013-06-05 at 10 27 42 pm](https://f.cloud.github.com/assets/684677/616104/be2865ca-ce59-11e2-928d-472f078aeefb.png)
![screen shot 2013-06-05 at 10 31 39 pm](https://f.cloud.github.com/assets/684677/616105/be2867fa-ce59-11e2-986d-78aae073b27a.png)
![screen shot 2013-06-05 at 10 30 35 pm](https://f.cloud.github.com/assets/684677/616106/be26c472-ce59-11e2-9d04-ca577cfc9ca7.png)

**Comment by patmalt** [comment] 2013-06-06 03:46
@KieranLafferty

**Comment by KieranLafferty** [comment] 2013-06-10 03:37
Hey Pat,

Thanks for the detailed info. I wasn't able to reproduce the issue on my end. I created a branch called Instantiated Programmatically which created the KLScrollingSelect in code (instead of using IB) if you wanted to take a look at it to see if I have done as you described.

Closing until response

**Closed as completed by KieranLafferty** 2013-06-10 03:37 UTC

**Comment by cja1** [comment] 2014-06-13 12:36
Hi,

I think the issue is that

```
- (UITableViewCell*) scrollSelect:(KLScrollSelect*) scrollSelect cellForRowAtIndexPath:(NSIndexPath *)indexPath;
```

should be

```
- (UITableViewCell*) scrollSelect:(KLScrollSelect*) scrollSelect cellForRowAtIndexPath:(KLIndexPath *)indexPath;
```

(NSIndexPath does not have a column property, KLIndexPath does)
